import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import localFont from "next/font/local";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={pretendard.className}>
        <div className="w-full flex justify-center">
          <div className="max-w-[600px] w-full h-screen bg-frame-image bg-cover">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
